name: Auto Deploy to Ubuntu Server

on:
  push:
    branches:
      - main  # Hoặc main

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/data/nfs/spark/spark
          git pull origin main
          echo "✅ Deploy thành công lúc $(date)"